/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vote-sys.h"


void
vote_prog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	voter_pack  changepassword_1_arg;
	char * *result_2;
	char *zeroize_1_arg;
	char * *result_3;
	voter_pack  addvoter_1_arg;
	char * *result_4;
	voter_pack  votefor_1_arg;
	char * *result_5;
	char *listcandidates_1_arg;
	char * *result_6;
	voter_pack  votecount_1_arg;
	char * *result_7;
	voter_pack  viewresult_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, VOTE_PROG, VOTE_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = changepassword_1(&changepassword_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = zeroize_1((void*)&zeroize_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = addvoter_1(&addvoter_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = votefor_1(&votefor_1_arg, clnt);
	if (result_4 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = listcandidates_1((void*)&listcandidates_1_arg, clnt);
	if (result_5 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = votecount_1(&votecount_1_arg, clnt);
	if (result_6 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = viewresult_1(&viewresult_1_arg, clnt);
	if (result_7 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	vote_prog_1 (host);
exit (0);
}
