/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTE-SYS_H_RPCGEN
#define _VOTE-SYS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct voter_pack {
	char command;
	char password[100];
	char username[100];
	char new_password[100];
	char cname[100];
	int voter_id;
};
typedef struct voter_pack voter_pack;

#define VOTE_PROG 0x29356488
#define VOTE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define changepassword 1
extern  char ** changepassword_1(voter_pack *, CLIENT *);
extern  char ** changepassword_1_svc(voter_pack *, struct svc_req *);
#define zeroize 2
extern  char ** zeroize_1(void *, CLIENT *);
extern  char ** zeroize_1_svc(void *, struct svc_req *);
#define addvoter 3
extern  char ** addvoter_1(voter_pack *, CLIENT *);
extern  char ** addvoter_1_svc(voter_pack *, struct svc_req *);
#define votefor 4
extern  char ** votefor_1(voter_pack *, CLIENT *);
extern  char ** votefor_1_svc(voter_pack *, struct svc_req *);
#define listcandidates 5
extern  char ** listcandidates_1(void *, CLIENT *);
extern  char ** listcandidates_1_svc(void *, struct svc_req *);
#define votecount 6
extern  char ** votecount_1(voter_pack *, CLIENT *);
extern  char ** votecount_1_svc(voter_pack *, struct svc_req *);
#define viewresult 7
extern  char ** viewresult_1(voter_pack *, CLIENT *);
extern  char ** viewresult_1_svc(voter_pack *, struct svc_req *);
extern int vote_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define changepassword 1
extern  char ** changepassword_1();
extern  char ** changepassword_1_svc();
#define zeroize 2
extern  char ** zeroize_1();
extern  char ** zeroize_1_svc();
#define addvoter 3
extern  char ** addvoter_1();
extern  char ** addvoter_1_svc();
#define votefor 4
extern  char ** votefor_1();
extern  char ** votefor_1_svc();
#define listcandidates 5
extern  char ** listcandidates_1();
extern  char ** listcandidates_1_svc();
#define votecount 6
extern  char ** votecount_1();
extern  char ** votecount_1_svc();
#define viewresult 7
extern  char ** viewresult_1();
extern  char ** viewresult_1_svc();
extern int vote_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_voter_pack (XDR *, voter_pack*);

#else /* K&R C */
extern bool_t xdr_voter_pack ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTE-SYS_H_RPCGEN */
